export default {
    INTERACTIVE_MODE_CARDBORAD_MOTION: 'CARDBOARD_MOTION',
    INTERACTIVE_MODE_CARDBORAD_MOTION_WITH_TOUCH: 'CARDBOARD_MOTION_WITH_TOUCH',
    INTERACTIVE_MODE_TOUCH: 'TOUCH',
    INTERACTIVE_MODE_MOTION: 'MOTION',
    INTERACTIVE_MODE_MOTION_WITH_TOUCH: 'MOTION_WITH_TOUCH',

    DISPLAY_MODE_GLASS: 'GLASS',
    DISPLAY_MODE_NORMAL: 'NORMAL',

    PROJECTION_MODE_SPHERE: 'SPHERE',
    PROJECTION_MODE_CUBE: 'CUBE',
}